name: Assignment workflow

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Assignment workflow

        run: |
          classroom_tools_url="https://github.com/ClassroomSuite/ClassroomTools"
          template_repo_fullname="INF1007-Gabarits/GabaritExercice"
          test_file="test_exercice.py"
          firebase_real_time_db_url="${{ secrets.FIREBASE_DB_URL }}"

          function update_student_repository() {
            printf '\n\n\n\n################################## Update student repository ##################################\n'
            python3 -m classroom_tools.student_repositories.sync_with_template_repository \
              --template_repo_fullname="$template_repo_fullname" \
              --as_student_repo_workflow
          }

          function show_grades_in_readme() {
            printf '\n\n\n\n#################################### Show grades in readme ####################################\n'
            # Create tests results
            python3 "$test_file"
            # Create grades from tests
            python3 -m classroom_tools.grading.create_grades
            # Update README
            python3 -m classroom_tools.grading.show_grades_in_readme
            # Push modifications
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add logs/tests_results.txt
            git add logs/grades.json
            git add README.md
            git commit -a -m "Updated autograding results"
            git pull -v --rebase=true
            git push -v
          }

          function patch_db() {
            printf '\n\n\n\n############################## Patch Firebase Realtime Database ###############################\n'
            python3 -m classroom_tools.grading.patch_db \
              --access_token="" \
              --firebase_real_time_db_url="$firebase_real_time_db_url" \
              --github_repo="$(basename $(pwd))"
          }

          python3 -m pip install -q setuptools
          python3 -m pip install -q git+"$classroom_tools_url"
          update_student_repository
          show_grades_in_readme
          patch_db
