# IMPORTANT: Only students workflows with repository_dispatch will be triggered
# You may specify an event_type to trigger specific workflows:
# on:
#   repository_dispatch:
#     types: [your_event_type] # optional. Will capture all types if not specified
#

name: Trigger students workflows

on:
  workflow_dispatch:
    inputs:
      org_name:
        description: "Name of organization with student repositories"
        required: true
      repo_filter:
        description: "Prefix to filter repositories for a given assignment or exercise"
        required: true
      event_type:
        description: "Event type shown in Actions (may be used to select specific workflows)"
        required: false
        default: "Manual trigger"

jobs:
  trigger_workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Trigger workflows
        run: |
          python3 -m pip install -q setuptools
          python3 -m pip install -q git+${{ secrets.CLASSROOM_TOOLS_URL }}
          python3 -m classroom_tools.student_repositories.trigger_workflows \
          --token=${{ secrets.REPO_WORKFLOW_PAT }} \
          --org_name=${{ github.event.inputs.org_name }} \
          --repo_filter=${{ github.event.inputs.repo_filter }} \
          --event_type="${{ github.event.inputs.event_type }}"
