# Change access permissions for all student repositories within an organization for a given assignment

# How to trigger this workflow
# 1. Verify if your organization secrets as a MANAGE_ACCESS secret and that this workflow as access to it
# 2. On GitHub, navigate to the main page of the repository.
# 3. Under your repository name, click Actions.
# 4. In the left sidebar, click the workflow you want to run.
# 5. Above the list of workflow runs, select Run workflow.
# 6. Select the branch where the workflow will run and type the input parameters used by the workflow. Click Run workflow.

name: Change access permissions

on:
  workflow_dispatch:
    inputs:
      classroom_tools_url:
        description: "ClassroomTools url"
        required: true
        default: "https://github.com/TestOrgJustAymeric/ClassroomTools"
      repo_filter:
        description: "Prefix to filter repositories for a given assignment or exercise"
        required: true
      permission_level:
        description: "Repo access (push or pull)"
        required: true
        default: "pull"
      
jobs:
  change_permission:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Apply permission
      run: |
        python3 -m pip install -q setuptools
        python3 -m pip install -q git+${{ github.event.inputs.classroom_tools_url }}
        python3 -m classroom_tools.student_repositories.access_permissions \
        --TOKEN=${{ secrets.MANAGE_ACCESS }} \
        --org_name="$GITHUB_REPOSITORY_OWNER" \
        --repo_filter=${{ github.event.inputs.repo_filter }} \
        --new_permission_level=${{ github.event.inputs.permission_level }}
