name: Create student repo
on:
  workflow_dispatch:
    inputs:
      template_repo_fullname:
        description: "Template repo fullname in format: OrgName/RepoName"
        required: true
      org_name:
        description: "Name of organization to hold the new repo"
        required: true
        default: "INF1007-2020A"
      repo_name:
        description: "Name of the repo to be created"
        required: true
      private:
        description: "Create private repository (true or false)"
        required: true
        default: "true"
      admin_collaborators:
        description: "Collaborator usernames to receive admin access"
        required: false
      write_collaborators:
        description: "Student Github login. And"
        required: false
      team_name:
        description: "Student's team name to receive write access"
        required: false

jobs:
  create_repos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create student repo
        run: |
          python3 -m pip install -q setuptools
          python3 -m pip install -q git+${{ secrets.CLASSROOM_TOOLS_URL }}
          python3 -m classroom_tools.student_repositories.create_student_repo \
            --token=${{ secrets.REPO_ADMIN_PAT }} \
            --template_repo_fullname=${{ github.event.inputs.template_repo_fullname }} \
            --org_name=${{ github.event.inputs.org_name }} \
            --repo_name=${{ github.event.inputs.repo_name }} \
            --private=${{ github.event.inputs.private }} \
            --admin_collaborators="${{ github.event.inputs.admin_collaborators }}" \
            --write_collaborators="${{ github.event.inputs.write_collaborators }}" \
            --team_name=${{ github.event.inputs.team_name }}
