# IMPORTANT: Only students workflows with repository_dispatch will be triggered
# You may specify an event_type to trigger specific workflows:
# on:
#   repository_dispatch:
#     types: [your_event_type] # optional. Will capture all types if not specified
#

# How to trigger this workflow
# 1. On GitHub, navigate to the main page of the repository.
# 2. Under your repository name, click Actions.
# 3. In the left sidebar, click the workflow you want to run.
# 4. Above the list of workflow runs, select Run workflow.
# 5. Select the branch where the workflow will run and type the input parameters used by the workflow. Click Run workflow.

name: Trigger students workflows

on:
  workflow_dispatch:
    inputs:
      classroom_tools_url:
        description: "ClassroomTools url"
        required: true
        default: "https://github.com/TestOrgJustAymeric/ClassroomTools"
      repo_filter:
        description: "Prefix to filter repositories for a given assignment or exercise"
        required: true
        default: "exercice"
      event_type:
        description: "Event type shown in Actions (may be used to select specific workflows)"
        required: false
        default: "Manual trigger"

jobs:
  trigger_workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Trigger workflows
        run: |
          python3 -m pip install -q setuptools
          python3 -m pip install -q git+${{ github.event.inputs.classroom_tools_url }}
          python3 -m classroom_tools.student_repositories.trigger_workflows \
          --TOKEN=${{ secrets.WORKFLOW }} \
          --org_name="$GITHUB_REPOSITORY_OWNER" \
          --repo_filter=${{ github.event.inputs.repo_filter }} \
          --event_type="${{ github.event.inputs.event_type }}"
