name: Update students workflows

on:
  workflow_dispatch:
    inputs:
      classroom_tools_url:
        description: "ClassroomTools url"
        required: true
        default: "https://github.com/ClassroomSuite/ClassroomTools"
      org_name:
        description: "Name of organization with student repositories"
        required: true
      repo_filter:
        description: "Prefix to filter repositories for a given assignment or exercise"
        required: true
      delete_previous_workflows:
        description: "Delete all workflows from each selected student repositories to prevent cheating (True or False)"
        required: true
        default: "True"
      new_workflow_files:
        description: "(optional) Path to %workflow%.yml files to add in students repositories"
        required: false

jobs:
  update_workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update workflows
        run: |
          python3 -m pip install -q setuptools
          python3 -m pip install -q git+${{ github.event.inputs.classroom_tools_url }}
          python3 -m classroom_tools.student_repositories.update_workflows \
          --token=${{ secrets.REPO_WORKFLOW_PAT }} \
          --org_name=${{ github.event.inputs.org_name }} \
          --repo_filter=${{ github.event.inputs.repo_filter }} \
          --delete_previous_workflows=${{ github.event.inputs.delete_previous_workflows }} \
          --new_workflow_files ${{ github.event.inputs.new_workflow_files }}
