# How to trigger this workflow
# 1. On GitHub, navigate to the main page of the repository.
# 2. Under your repository name, click Actions.
# 3. In the left sidebar, click the workflow you want to run.
# 4. Above the list of workflow runs, select Run workflow.
# 5. Select the branch where the workflow will run and type the input parameters used by the workflow. Click Run workflow.

name: Update student workflows

on:
  workflow_dispatch:
    inputs:
      classroom_tools_url:
        description: "ClassroomTools url"
        required: true
        default: "https://github.com/TestOrgJustAymeric/ClassroomTools"
      repo_filter:
        description: "Prefix to filter repositories for a given assignment or exercise"
        required: true
        default: "exercice"
      delete_previous_workflows:
        description: "Delete all workflows from each selected student repositories to prevent cheating (True or False)"
        required: true
        default: "True"
      new_workflow_files:
        description: "(optinal) A path to a %workflow%.yml file to add in students repositories"
        required: false
        default: ".github/student_workflows/classroom_actions.yml"

jobs:
  update_workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update workflows
        run: |
          python3 -m pip install -q setuptools
          python3 -m pip install -q git+${{ github.event.inputs.classroom_tools_url }}
          python3 -m classroom_tools.student_repositories.update_workflows \
          --TOKEN=${{ secrets.WORKFLOW }} \
          --org_name="$GITHUB_REPOSITORY_OWNER" \
          --repo_filter=${{ github.event.inputs.repo_filter }} \
          --delete_previous_workflows=${{ github.event.inputs.delete_previous_workflows }} \
          --new_workflow_files ${{ github.event.inputs.new_workflow_files }}
